Repository mbirali/angular-starter, pull requests merged in 2025-04, with the labels that each got.

#33 Format readme file
  README.md
Labels: documentation, enhancement, good first issue

#36 Prefix only on commits
  CONTRIBUTING.md
Labels: documentation, enhancement

#39 Generate new Angular app
  angular.json
  package-lock.json
  package.json
  projects/auto-crud/public/favicon.ico
  projects/auto-crud/src/app/app.component.ts
  projects/auto-crud/src/app/app.config.ts
  projects/auto-crud/src/app/app.routes.ts
  projects/auto-crud/src/index.html
  projects/auto-crud/src/main.ts
  projects/auto-crud/src/styles.scss
  projects/auto-crud/tsconfig.app.json
Labels: enhancement
